#!/bin/bash
# Shebang is for Terraform script provisioner

REPO_URL=https://github.com/rchain/rchain-collectd-server
REPO_DIR=/opt/rchain-collectd-server
GIT_CRYPT_KEY_FILE=/root/rchain-sre-git-crypt-key
SETUP_SCRIPT_URL=https://raw.githubusercontent.com/rchain/rchain-collectd-server/master/update-run-setup

if [[ -z "$SETUP_SCRIPT_RUNNING" ]]; then
	source <(curl -fsSL "$SETUP_SCRIPT_URL")
fi
