#!/bin/bash
set -e -o pipefail

apt install -y librrd8
librrd_ver="$(dpkg-query -W -f '${Version}' librrd8)"
if dpkg --compare-versions $librrd_ver lt '1.7.1'; then
	librrd_url='http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/r/rrdtool/librrd8_1.7.1-1_amd64.deb'
	librrd_deb="$(basename "$librrd_url")"
	pushd /tmp
	curl -fsSLO "$librrd_url"
	apt install -y ./$librrd_deb
	rm $librrd_deb
	popd
fi

apt install -y --no-install-recommends \
    apt-transport-https gnupg2 \
    collectd liboping0

install -C -m644 collectd.conf -t /etc/collectd/
systemctl restart collectd
